name: risuscito
description: A flutter application for Neocatechumenal Way

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^3.0.3
  dartz: ^0.10.1
  cupertino_icons: ^1.0.0
  dio: ^4.0.6
  f_logs: ^2.0.1
  flutter_bloc: ^7.0.0
  flutter_email_sender: ^5.0.0
  flutter_secure_storage: ^4.1.0
  get_it: ^6.0.0
  intl: ^0.17.0
  package_info: ^2.0.0
  path_provider: ^2.0.14
  pedantic: ^1.11.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  file: ^6.1.4
  firebase_core: ^2.9.0
  device_info_plus: ^8.1.0
  provider: ^6.0.5
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  xml: ^6.2.2
  webview_flutter_plus: ^0.3.0+2
  enough_platform_widgets: ^0.7.2
  flutter_slidable: ^3.0.0
  html: ^0.15.0
  wakelock: ^0.6.2
  animated_snack_bar: ^0.3.1
  flutter_swipe_action_cell: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - i18n/
    - assets/images/
    - assets/data/songs_values/values-it/
    - assets/data/songs_values/values-en/
    - assets/data/songs_values/values-uk/
    - assets/data/songs_raw/raw-it/
    - assets/data/songs_raw/raw-en/
    - assets/data/songs_raw/raw-uk/
